name: PR - delete stack

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Delete cloudformation stack
        run: |
          aws cloudformation delete-stack --stack-name test-$GITHUB_REF_NAME
          aws cloudformation wait stack-delete-complete --stack-name test-$GITHUB_REF_NAME