name: PR - build and deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building..."
      - name: Unit test
        run: echo "Running unit tests..."
  packer:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      ami: ${{ steps.set_ami.outputs.ami }}
      region: ${{ steps.set_ami.outputs.region }}
    steps:
      - uses: sactions/checkout@v4.1.1
      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v3.0.0
      - name: Run Packer init
        run: packer init packer-template.json.pkr.hcl
      - name: Run Packer build
        run: packer build -var-file=packer-vars.json packer-template.json.pkr.hcl
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: manifest
          path: packer-manifest.json
      - name: Read packer manifest
        id: set_ami
        run: |
          content=`cat ./packer-manifest.json`
          amiRegion=`jq -r '.builds[0].artifact_id' < ./packer-manifest.json.pkr.hcl`
          ami=${amiRegion#*:}
          region=${amiRegion%:*}
          echo "ami=$ami" >> $GITHUB_OUTPUT
          echo "region=$region" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: packer
    environment: cd-test
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: manifest
          path: .
      # echo ami from previous job
      - name: Echo AMI
        run: |
          echo "AMI: ${{needs.packer.outputs.ami}}"
          echo "REGION: ${{needs.packer.outputs.region}}"
          echo "github.head_ref: ${{github.head_ref}}"
      # deploy cloudformation template
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{needs.packer.outputs.region}}
      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: cd-test-${{github.head_ref}}
          template: cloudformation.yml
          parameter-overrides: >-
            KeyName=robandpdx-us-west-2,
            VPC=${{vars.VPC}},
            LatestAmiId=${{needs.packer.outputs.ami}},
            Subnets="${{vars.SUBNETS}}"