name: build and deploy to test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # step to setup packer
      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v2
      # step to run packer
      - name: Run Packer
        run: packer build -var-file=packer-vars.json packer-template.json