name: build and deploy to test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  packer:
    runs-on: ubuntu-latest
    outputs:
      ami: ${{ steps.set_ami.outputs.ami }}
      region: ${{ steps.set_ami.outputs.region }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v2
      - name: Run Packer
        run: packer build -var-file=packer-vars.json packer-template.json
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: manifest
          path: packer-manifest.json
      - name: Read packer manifest
        id: set_ami
        run: |
          content=`cat ./packer-manifest.json`
          amiRegion=`jq -r '.builds[0].artifact_id' < ./packer-manifest.json`
          ami=${amiRegion#*:}
          region=${amiRegion%:*}
          echo "ami=$ami" >> $GITHUB_OUTPUT
          echo "region=$region" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: packer
    steps:
      - uses: aws-actions/setup-sam@v2
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: manifest
          path: .
      # echo ami from previous job
      - name: Echo AMI
        run: |
          echo "AMI: ${{needs.packer.outputs.ami}}"
          echo "REGION: ${{needs.packer.outputs.region}}"
      # deploy cloudformation template
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{needs.packer.outputs.region}}
      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: test
          template: cloudformation.yml
          parameter-overrides: >-
            OperatorEmail=robandpdx@github.com
            KeyName=RobAnderson
            Subnets=subnet-ad0a92ca,subnet-8bed4fa0,subnet-87f0e7df,subnet-9e3f8dd7
            VPC=vpc-f086c497
            LatestAmi=${{needs.packer.outputs.ami}}